<?php

/**
 * CategoriaCervezaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaCervezaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaCervezaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoriaCerveza');
    }
}