<?php

/**
 * CervezaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CervezaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CervezaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cerveza');
    }
}