<?php

/**
 * ConfigsCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfigsCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfigsCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConfigsCategory');
    }
}