<?php

/**
 * GenerosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GenerosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GenerosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Generos');
    }
}