<?php

/**
 * GroupPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupPermission');
    }
}