<?php

/**
 * InmuebleCaracteristicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InmuebleCaracteristicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InmuebleCaracteristicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InmuebleCaracteristica');
    }
}