<?php

/**
 * InmuebleTipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InmuebleTipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InmuebleTipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InmuebleTipo');
    }
}