<?php

/**
 * ParametroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParametroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParametroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parametro');
    }
}