<?php

/**
 * PatrocinadorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PatrocinadorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PatrocinadorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Patrocinador');
    }
}