<?php

/**
 * PerfilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerfilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerfilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Perfiles');
    }
}