<?php

/**
 * PermissionTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PermissionTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PermissionTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PermissionType');
    }
}