<?php

/**
 * PlazasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlazasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlazasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plazas');
    }
}