<?php

/**
 * PropiedadCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PropiedadCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PropiedadCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PropiedadCategoria');
    }
}