<?php

/**
 * ReservaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReservaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReservaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reserva');
    }
}