<?php

/**
 * UploadsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UploadsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UploadsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Uploads');
    }
}