<?php

/**
 * UsersGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsersGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsersGroup');
    }
}