<?php

/**
 * UsuarioWebTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioWebTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioWebTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioWeb');
    }
}