<?php

/**
 * VideojuegosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideojuegosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideojuegosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Videojuegos');
    }
}